name: Format with Prettier

on:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Prettier
        run: npm install -g prettier

      - name: Run Prettier
        run: prettier . --write

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Format code with Prettier" || echo "No changes to commit"
          git push
